# Generated by Django 3.0.6 on 2020-11-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201103_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=500)),
                ('adress', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
            ],
        ),
    ]
