# Generated by Django 3.0.6 on 2020-11-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='networth',
            field=models.SmallIntegerField(default=0),
        ),
    ]
