# Generated by Django 3.0.6 on 2020-11-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_networth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trdelnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=50)),
                ('trdelnik_type', models.CharField(max_length=500)),
                ('pomazka_type', models.CharField(max_length=500)),
                ('posypka_type', models.CharField(max_length=500)),
                ('nachinka_type', models.CharField(max_length=500)),
                ('iceCream_type', models.CharField(max_length=500)),
                ('Topping_type', models.CharField(max_length=500)),
                ('Decorations_type', models.CharField(max_length=500)),
                ('Adress_type', models.CharField(max_length=500)),
            ],
        ),
    ]
